// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX3_61LgFwE3xARyYsE4rYLdylMK27xmQ',
    appId: '1:302605183636:web:ed3506f9245a6ee7cfe281',
    messagingSenderId: '302605183636',
    projectId: 'diary-app-ui',
    authDomain: 'diary-app-ui.firebaseapp.com',
    storageBucket: 'diary-app-ui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUiKvkxDVKvO9LswbReKI79gsvQ2lEkBM',
    appId: '1:302605183636:android:a11fc185165ba80ccfe281',
    messagingSenderId: '302605183636',
    projectId: 'diary-app-ui',
    storageBucket: 'diary-app-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyAY8lFfwJ9LGe9AMC9iaZa9cHey4xg-U',
    appId: '1:302605183636:ios:697aeb81744eb5d6cfe281',
    messagingSenderId: '302605183636',
    projectId: 'diary-app-ui',
    storageBucket: 'diary-app-ui.appspot.com',
    iosClientId: '302605183636-cooolu448lg9maeskgfufllm66b7cjof.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyAY8lFfwJ9LGe9AMC9iaZa9cHey4xg-U',
    appId: '1:302605183636:ios:7d98589322520eb9cfe281',
    messagingSenderId: '302605183636',
    projectId: 'diary-app-ui',
    storageBucket: 'diary-app-ui.appspot.com',
    iosClientId: '302605183636-8vqvp6dr509qf5o8k6i1n7073lmb6ice.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp.RunnerTests',
  );
}
